services
  - type web
    name nodejs
    region frankfurt
    repo "https://github.com/Azdhar-Wout/esgi.4a.render.blueprint.nodejs"
    runtime node
    """
    key: PLSQL_PASSWORD
    fromService:
      name: mysql
      type: pserv
      envVarKey: PASSWORD
      """
 